### ISSUE TITLE
incorrect peer dependencies - React 17 Support

### ISSUE THREAD

**Issue by CWSites** [react-theming/storybook-addon#20] opened 2021-05-18 19:48 UTC
Running my `e2e` tests using cypress I get the following warnings in my CLI. I'm on `v1.1.1`. Is there any way to fix these? It's really annoying to see a ton of warnings.

```
warning " > @react-theming/storybook-addon@1.1.1" has unmet peer dependency "@storybook/theming@^5.0.0 || ^6.0.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit@1.4.1" has unmet peer dependency "@storybook/addons@^5.0.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit@1.4.1" has incorrect peer dependency "@storybook/react@^5.0.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit@1.4.1" has incorrect peer dependency "react@^16.0.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit@1.4.1" has incorrect peer dependency "react-dom@^16.0.0".
warning "@react-theming/storybook-addon > @usulpro/react-json-view@2.0.1" has incorrect peer dependency "react@^16.0.0 || ^15.5.4".
warning "@react-theming/storybook-addon > @usulpro/react-json-view@2.0.1" has incorrect peer dependency "react-dom@^16.0.0 || ^15.5.4".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect@0.2.1" has incorrect peer dependency "react@^16.8.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect@0.2.1" has incorrect peer dependency "react-dom@^16.8.0".
warning "@react-theming/storybook-addon > @usulpro/react-json-view > react-textarea-autosize@6.1.0" has incorrect peer dependency "react@>=0.14.0 <17.0.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect > @reach/component-component@0.1.3" has incorrect peer dependency "react@^16.4.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect > @reach/component-component@0.1.3" has incorrect peer dependency "react-dom@^16.4.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @storybook/addons > @storybook/api > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
```

**Comment by CWSites** [comment] 2021-06-25 13:57
It would be nice if this could get updated to use latest `react`

**Comment by UsulPro** [comment] 2021-06-25 17:15
Sure @CWSites I think we can do it safely! Fell free to add a PR for that. It will be really appreciated!

**Comment by CWSites** [comment] 2021-06-29 19:18
> Sure @CWSites I think we can do it safely! Fell free to add a PR for that. It will be really appreciated!

I'll do my best but extremely busy with work.

**Comment by KASOGIT** [comment] 2021-07-06 10:21
Hi, same problem here, it would be nice that addon-devkit accept @storybook/react@^6.0.0
![image](https://user-images.githubusercontent.com/15908751/124584484-97c7b980-de54-11eb-9efa-78d3ff75c2a1.png)

**Comment by JettScythe** [comment] 2021-08-08 18:00
Same issue. Started a project with `npx create-next-app` `npx sb init` & `npm i @react-theming/storybook-addon` and getting the output 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @storybook/react@6.3.6
npm ERR! node_modules/@storybook/react
npm ERR!   dev @storybook/react@"^6.3.6" from the root project
npm ERR!   peer @storybook/react@"^5.0.0 || ^6.0.0" from @react-theming/storybook-addon@1.1.1
npm ERR!   node_modules/@react-theming/storybook-addon
npm ERR!     @react-theming/storybook-addon@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/react@"^5.0.0" from @storybook/addon-devkit@1.4.1
npm ERR! node_modules/@react-theming/storybook-addon/node_modules/@storybook/addon-devkit
npm ERR!   @storybook/addon-devkit@"^1.4.1" from @react-theming/storybook-addon@1.1.1
npm ERR!   node_modules/@react-theming/storybook-addon
npm ERR!     @react-theming/storybook-addon@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/anon/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anon/.npm/_logs/2021-08-08T17_57_15_060Z-debug.log

```

**Comment by CWSites** [comment] 2021-11-03 18:13
@UsulPro discussed with the storybook folks and they mentioned that you should no longer be using the `@storybook/addon-devkit` as the APIs have moved to storybook itself. See more details here: https://github.com/storybookjs/storybook/issues/16557. What are your thoughts?

**Comment by CWSites** [comment] 2021-11-03 18:21
@JettScythe, it looks like you're missing other peer dependencies. Can you verify that you have the following installed?

> @storybook/react@"^5.0.0"

**Comment by JettScythe** [comment] 2021-11-03 18:48
@CWSites I can confirm I have the following: 
```"@storybook/addon-actions": "^6.3.6",
        "@storybook/addon-essentials": "^6.3.6",
        "@storybook/addon-links": "^6.3.6",
        "@storybook/react": "^6.3.6",

**Comment by CWSites** [comment] 2021-11-03 18:49
@JettScythe thanks, I had to do the same and wasn't going to revert to an earlier version of `@storybook/react`. Hopefully it will get fixed soon :)

**Comment by UsulPro** [comment] 2021-11-03 19:38
@CWSites 
> is there a reason that you forked react-json-view, 
I had to fork it at the moment when this package wasn't maintained and the author didn't respond. Now we have an extra feature to show colors. I know the maintainer came back and updated the repo so I did a PR to the original. But it still isn't merged and I'm afraid it's outdated now. 

>they mentioned that you should no longer be using the @storybook/addon-devkit as the APIs have moved to storybook itself
answered there

**Comment by UsulPro** [comment] 2021-11-03 19:43
Fixing peerDependencies in addon-devkit would be enough to solve this?

**Comment by CWSites** [comment] 2021-11-04 03:59
@UsulPro I believe so, would it be possible to get around the need to use `addon-devkit`?

**Comment by UsulPro** [comment] 2021-11-14 19:05
Guys! I believe we can close it finally as I've updated dependencies. Let me know if there are any issues yet?

**Closed by UsulPro** 2021-11-14 19:05 UTC

**Comment by slipo** [comment] 2021-11-30 20:01
I believe this still doesn't work with React 17 because of [this line.](https://github.com/UsulPro/react-json-view/blob/master/package.json#L41) @UsulPro

**Comment by CWSites** [comment] 2022-01-06 18:00
Still getting the following as of latest today
```
warning "@react-theming/storybook-addon > @usulpro/react-json-view@2.0.1" has incorrect peer dependency "react@^16.0.0 || ^15.5.4".
warning "@react-theming/storybook-addon > @usulpro/react-json-view@2.0.1" has incorrect peer dependency "react-dom@^16.0.0 || ^15.5.4".
warning "@react-theming/storybook-addon > @usulpro/react-json-view > react-textarea-autosize@6.1.0" has incorrect peer dependency "react@>=0.14.0 <17.0.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect@0.2.1" has incorrect peer dependency "react@^16.8.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect@0.2.1" has incorrect peer dependency "react-dom@^16.8.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect > @reach/component-component@0.1.3" has incorrect peer dependency "react@^16.4.0".
warning "@react-theming/storybook-addon > @storybook/addon-devkit > @reach/rect > @reach/component-component@0.1.3" has incorrect peer dependency "react-dom@^16.4.0".
```

**Comment by CWSites** [comment] 2022-01-06 19:06
@UsulPro see above, still a few issues here.
